name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  generate_changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      
      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate Changelog
        run: |
          git fetch --tags --force
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          github_changelog_generator -u confy-security -p cli --since-tag $latest_tag
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
      
      - name: Upload CHANGELOG file
        uses: actions/upload-artifact@v5
        with:
          name: CHANGELOG
          path: CHANGELOG.md

  publish:
    name: Publish Package to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/confy-cli/
    permissions:
      id-token: write
      contents: write
      packages: write
      actions: write
      discussions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Package project
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
    
      - name: Download CHANGELOG artifact
        uses: actions/download-artifact@v5
        with:
          name: CHANGELOG
          path: .
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          body_path: ./CHANGELOG.md

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version from git tags
        id: version
        run: echo "VERSION=$(git describe --tags --always | cut -d'-' -f1)" >> "$GITHUB_OUTPUT"
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/confy-security/${{ github.repository }}:latest
            ghcr.io/confy-security/${{ github.repository }}:${{ steps.version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64